trigger:
  - dev

pool:
  vmImage: ubuntu-latest

steps:
  - task: Maven@4
    displayName: 'Maven Build and Compile'
    inputs:
      mavenPomFile: 'pom.xml'
      goals: 'clean compile'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.17'

  - script: |
      mvn exec:java -e -D exec.mainClass=com.microsoft.playwright.CLI -D exec.args="install --with-deps"
    displayName: 'Install Playwright Browsers'

  - script: mvn test
    displayName: 'Run Automated Tests'